ALTER TABLE register
ADD student_id int;

ALTER TABLE register
ADD CONSTRAINT 
FOREIGN KEY (student_id) REFERENCES students(student_id)
ON DELETE CASCADE
ON UPDATE CASCADE;


ALTER TABLE student_bills
ADD CONSTRAINT 
FOREIGN KEY (student_id) REFERENCES students(student_id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE student_bills
ADD CONSTRAINT 
FOREIGN KEY (bill_id) REFERENCES bills(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE student_payment
ADD CONSTRAINT 
FOREIGN KEY (student_id) REFERENCES students(student_id)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE student_payment
ADD CONSTRAINT 
FOREIGN KEY (bill_id) REFERENCES bills(id)
ON DELETE SET NULL
ON UPDATE CASCADE;

